<?php
session_start();
unset($_SESSION["user_id"]);
unset($_SESSION["user_name"]);
unset($_SESSION["user_email"]);
unset($_SESSION["user_login_email"]);
unset($_SESSION["gmail_login"]);
session_destroy(); 
header("Location:index.php");
?>