widgetTheme=widget-themes/oval
primaryColor=#f0545c
secondaryColor=#f0545c
labelColor=#ffffff
hideWhenOffline=false
contactMail=thamizha333@gmail.com
loadingLabel=Loading...
loginError=Login error
chatHeader=Talk to us
startInfo=Please fill the following form to start the chat
widgetWidth=337
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Start
backLabel=Back
initMessageBody=Hello, how may I help you?
initMessageAuthor=Operator
chatInputLabel=Write your question
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=Operator went off-line
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=End the chat
endChatConfirmQuestion=Are you sure?
endChatConfirm=Yes
endChatCancel=Cancel
contactHeader=Contact us
contactInfo=All operators are off-line. Use the below form to send us an e-mail with your question.
contactNameLabel=Your name
contactMailLabel=Your e-mail
contactQuestionLabel=Your question
contactSendLabel=Send
contactSuccessHeader=Message sent
contactSuccessMessage=Your question has been sent. Thank you!
contactErrorHeader=Error
contactErrorMessage=There was an error sending your question
headerHeight=45
installed=1
autoShowWidgetAfter=5
autoShowWidget=false
askForMail=false
